import Login from "../../components/Login";
import Passport from "../../components/passport";
import styles from "../../styles/login.module.scss";
import Head from "next/head";

export default function login() {
  return (
    <div className={styles.main}>
      <Head>
        <title>AlloMallem - login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Login />
        <div className={styles.separator}></div>
        <Passport />
      </div>
    </div>
  );
}
